close all;
clear all;
z = importdata('zaccels.txt');
z = transpose(z);
zraw = z(1,:);
zfir = z(2,:);
Z = fft(zraw);
t = linspace(0,size(zraw,2)*(1/25),size(zraw,2))
figure(1);
plot(t,zraw);
xlabel('time (sec)');
ylabel('Z accleration (g)');
title('raw data Z acceleration plot');
figure(2);
plot(t,zfir);
xlabel('time (sec)');
ylabel('Z accleration (g)');
title('Z acceleration with MAF plot');
figure(3);
plotFFT(zraw);
figure(4);
plotFFT(zfir);